name: CHOP
options:
  bundleIdPrefix: com.chop
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  CHOP:
    type: application
    platform: iOS
    sources:
      - path: CHOP
        excludes:
          - "**/.DS_Store"
    resources:
      - path: CHOP/Resources/Assets.xcassets
      - path: CHOP/Resources/Sounds
      - path: CHOP/Resources/Fonts
    settings:
      base:
        INFOPLIST_FILE: CHOP/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.chop.game
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: true
    entitlements:
      path: CHOP/Resources/CHOP.entitlements
      properties:
        com.apple.developer.game-center: true

  CHOPTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CHOPTests
    dependencies:
      - target: CHOP
    settings:
      base:
        INFOPLIST_FILE: CHOPTests/Info.plist

  CHOPUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: CHOPUITests
    dependencies:
      - target: CHOP
    settings:
      base:
        INFOPLIST_FILE: CHOPUITests/Info.plist

schemes:
  CHOP:
    build:
      targets:
        CHOP: all
        CHOPTests: [test]
        CHOPUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - CHOPTests
        - CHOPUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
